### ISSUE TITLE
CONTRACT_VALIDATE_ERROR when running migrate

### ISSUE THREAD

**Issue by victor-ponce** [Tronbox-boxes/metacoin-box#8]
Getting this error when running `tronbox migrate --reset`

```
> bash scripts/migrate-and-setup.sh

Using network 'shasta'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Unknown error: {
  "code": "CONTRACT_VALIDATE_ERROR",
  "message": "636f6e74726163742076616c6964617465206572726f72203a206163636f756e74206e6f7420657869737473"
}
```

**Comment by victor-ponce** [comment]
This seems to have been an issue in tronbox and was resolved when I updated it to the latest (currently 2.2.2)

**Comment by victor-ponce** [comment]
So the issue is still present if it uses the shasta network. It works fine with the development network.

`tronbox migrate --reset --network development` works fine
but `tronbox migrate --reset --network shasta` gives the contract validation error.

Since migrate-and-setup.sh uses the shasta network the `npm run setup-dapp` command fails unless you change the sh script to use the develompent network. It seems that all the code is supposed to use the development network anyway so maybe this just needs to be updated.

Side note, on Windows 10 you have to install the windows-build-tools npm package for this project:
`npm install -g --production windows-build-tools`

**Comment by sullof** [comment]
I guess you are running latest TronBox 2.2.2.
When someone can deploy on Tron Quickstart but cannot deploy on Shasta, usually, means that they don't have enough energy in the Shasta account. Can you verify that?

**Comment by victor-ponce** [comment]
Ahh...that must be it. I have TRX but no energy. Thanks, I'll try that.

**Comment by victor-ponce** [comment]
> I guess you are running latest TronBox 2.2.2.
> When someone can deploy on Tron Quickstart but cannot deploy on Shasta, usually, means that they don't have enough energy in the Shasta account. Can you verify that?

Yes, that was the issue. It's working now, thank you! Is there a chat room somewhere to ask things like how this project is configured and how it works, etc? Basically, general TRON dev questions. I don't think they'd be appropriate here.
